pipeline{
    agent any

    stages{
        stage('Build'){
            steps{
               myFunc("Hello")
            }
        }
        
    }
}

def myFunc(String myText){
    echo "myText is : ${myText}"
}