pipeline{
    agent any
    parameters{
        booleanParam(defaultValue: false,description: 'Enable Service',name: 'myBoolean')
    }
    stages{
        stage('Demo'){
            steps{
                echo "booleanparam is set to : ${params.myBoolean}"
            }
        }
    }
}