pipeline{
    agent any
    parameters{
        string(defaultValue: "Test",description: 'Which env to deploy',name: 'deployEnv')
    }
    stages{
        stage('Demo'){
            steps{
                echo "String is set to : ${params.deplyEnv}"
            }
        }
    }
}